name: Flutter APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: |
          flutter pub get
      - name: Create Android project if missing
        run: |
          flutter create .
      - name: Build APK (release)
        run: |
          flutter build apk --release -t lib/main.dart
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: finance-apk
          path: build/app/outputs/flutter-apk/app-release.apk
